# Generated by Django 4.2.1 on 2023-06-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reel_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('reel_id', models.AutoField(primary_key=True))
                ('reel_no', models.CharField(max_length=200)),
                ('reel_gsm', models.CharField(max_length=200)),
                ('reel_weight', models.CharField(max_length=200)),
                ('reel_size', models.CharField(max_length=200)),
                ('reel_date', models.DateField()),
            ],
        ),
    ]
