# Generated by Django 4.2.1 on 2023-06-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reel_byweight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reel_gsm', models.BigIntegerField(max_length=200)),
                ('reel_weight', models.BigIntegerField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_gsm',
            field=models.BigIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_no',
            field=models.BigIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_size',
            field=models.BigIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_weight',
            field=models.BigIntegerField(max_length=200),
        ),
    ]
