# Generated by Django 4.2.1 on 2023-06-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_reel_gsm_reel_byweight_gsm_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reel_byweight',
        ),
    ]
