# Generated by Django 4.2.1 on 2023-06-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_reel_byweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel_entry',
            name='reel_mill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reel_entry',
            name='reel_rate',
            field=models.BigIntegerField(blank=True, max_length=200, null=True),
        ),
    ]
