# Generated by Django 4.2.1 on 2023-06-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_reel_entry_reel_mill_reel_entry_reel_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel_entry',
            name='reel_balance',
            field=models.BigIntegerField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='reel_entry',
            name='reel_utilization',
            field=models.BigIntegerField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='reel_entry',
            name='reel_waste',
            field=models.BigIntegerField(default=0, max_length=200),
        ),
    ]
