# Generated by Django 4.2.1 on 2023-06-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_reel_entry_reel_balance_reel_entry_reel_utilization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel_entry',
            name='reel_amount',
            field=models.BigIntegerField(default=0, max_length=200),
        ),
    ]
