# Generated by Django 4.2.1 on 2023-06-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_reel_entry_reel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_gsm',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_no',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_size',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_utilization',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_waste',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_weight',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
