# Generated by Django 4.2.1 on 2023-06-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_reel_entry_reel_gsm_alter_reel_entry_reel_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_date',
            field=models.DateField(null=True),
        ),
    ]
