# Generated by Django 4.2.1 on 2023-06-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_reel_entry_reel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_balance',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_gsm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_utilization',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_waste',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reel_entry',
            name='reel_weight',
            field=models.IntegerField(null=True),
        ),
    ]
