# Generated by Django 4.2.1 on 2023-06-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_reel_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel_transactions',
            name='reel_time_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
